apiVersion: v2
name: azure-cloud-node-manager-app
description: A Helm chart for the Azure Cloud Node Manager.
version: 2.1.0-dev
appVersion: 1.34.3
home: https://github.com/giantswarm/azure-cloud-node-manager-app
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
  io.giantswarm.application.team: phoenix
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/azure/1/dark.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
